### ISSUE TITLE
Fatal error if no current issue

### ISSUE THREAD

**Issue by NateWr** [pkp/immersion#2]
The homepage results in a fatal error if no issue has been published. I think this will also happen if there is no "current" issue.

```
[04-Dec-2018 11:09:17 Europe/London] PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /home/nate/Projects/pkp/ojstemp/plugins/themes/immersion/ImmersionThemePlugin.inc.php:110
Stack trace:
#0 /home/nate/Projects/pkp/ojstemp/lib/pkp/classes/plugins/HookRegistry.inc.php(107): ImmersionThemePlugin->addIssueTemplateData('TemplateManager...', Array)
#1 /home/nate/Projects/pkp/ojstemp/lib/pkp/classes/template/PKPTemplateManager.inc.php(856): HookRegistry::call('TemplateManager...', Array)
#2 /home/nate/Projects/pkp/ojstemp/pages/index/IndexHandler.inc.php(75): PKPTemplateManager->display('frontend/pages/...')
#3 /home/nate/Projects/pkp/ojstemp/lib/pkp/classes/core/PKPRouter.inc.php(390): IndexHandler->index(Array, Object(Request))
#4 /home/nate/Projects/pkp/ojstemp/lib/pkp/classes/core/PKPPageRouter.inc.php(232): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array, false)
#5 /home/nate/Projects/pkp/ojstemp/lib/pkp/classes/core/Dispatcher.inc.php(134): PKPPageRouter->route(Object(Request))
#6 /home/nate/Projects/pkp/ in /home/nate/Projects/pkp/ojstemp/plugins/themes/immersion/ImmersionThemePlugin.inc.php on line 110
```

**Comment by Vitaliy-1** [comment]
Thanks! That's an important one.
